POST http://localhost:8080/api/hotels HTTP/1.1
content-type: application/json

{
  "name": "Hotel Joakim",
  "title": "The very luxurious hotel",
  "description": "Description of hotel",
  "type": "hotel",
  "city": "Copenhagen",
  "address": "Street",
  "distance": "500",
  "photos": [],
  "rating": 5,
  "rooms": [],
  "cheapestPrice": 100
}

###

PUT http://localhost:8080/api/hotels/628a7c89edd136f982090a67 HTTP/1.1
content-type: application/json

{
  "name": "Hotel Joakim updated",
  "title": "The very luxurious hotel",
  "description": "Description of hotel",
  "type": "hotel",
  "city": "Copenhagen",
  "address": "Street 501 boulevard",
  "distance": "500",
  "photos": [],
  "rating": 5,
  "rooms": [],
  "cheapestPrice": 100,
  "features": true
}

###

DELETE  http://localhost:8080/api/hotels/628a7c89edd136f982090a67 HTTP/1.1
content-type: application/json

###

GET  http://localhost:8080/api/hotels/628a7c89edd136f982090a67 HTTP/1.1
content-type: application/json

###

GET  http://localhost:8080/api/hotels HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/api/auth/register HTTP/1.1
content-type: application/json

{
  "username": "Joakim2",
  "email": "Joakim@email.com",
  "password": "secret"
}

###

POST http://localhost:8080/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "Joakim2",
  "password": "secret"
}

###

GET  http://localhost:8080/api/users HTTP/1.1
content-type: application/json

###

GET  http://localhost:8080/api/users/628fa6be716891a2262f7f98 HTTP/1.1
content-type: application/json

###

PUT http://localhost:8080/api/users/628fa6be716891a2262f7f98 HTTP/1.1
content-type: application/json

{
  "username": "Joakim updated",
  "password": "secret"
}

###

GET http://localhost:8080/api/users/checkuser/628fa6be716891a2262f7f9 HTTP/1.1