POST http://localhost:8080/api/lodgings HTTP/1.1
content-type: application/json

{
  "name": "Hotel Joakim",
  "title": "The very luxurious hotel",
  "description": "Description of hotel",
  "type": "hotel",
  "city": "Copenhagen",
  "address": "Street",
  "distance": "500",
  "photos": [],
  "rating": 5,
  "rooms": [],
  "cheapestPrice": 100
}

###

lodgingscontent-type: application/json

{
  "name": "Hotel Joakim updated",
  "title": "The very luxurious hotel",
  "description": "Description of hotel",
  "type": "hotel",
  "city": "Copenhagen",
  "address": "Street 501 boulevard",
  "distance": "500",
  "photos": [],
  "rating": 5,
  "rooms": [],
  "cheapestPrice": 100,
  "features": true
}

### DELETE LODGING

DELETE  http://localhost:8080/api/lodgings/628a7c89edd136f982090a67 HTTP/1.1
content-type: application/json

### LODGING DETAILS

GET  http://localhost:8080/api/lodgings/628a7c89edd136f982090a67 HTTP/1.1
content-type: application/json

### LODGING COUNT BY CITY

GET  http://localhost:8080/api/lodgings/countByCity?cities=london,copenhagen HTTP/1.1
content-type: application/json

### LODGING COUNT BY PROPERTY TYPE

GET  http://localhost:8080/api/lodgings/countByType HTTP/1.1
content-type: application/json

### FEATURED LODGINGS

GET  http://localhost:8080/api/lodgings?featured=true&limit=4 HTTP/1.1
content-type: application/json

### ALL LODGINGS

GET  http://localhost:8080/api/lodgings HTTP/1.1
content-type: application/json

### ALL ROOMS FOR LODGING

GET  http://localhost:8080/api/lodgings/room/62fbf8d3c48afe0684de5362 HTTP/1.1
content-type: application/json

### SIGN UP

POST http://localhost:8080/api/auth/register HTTP/1.1
content-type: application/json

{
  "username": "Joakim2",
  "email": "Joakim@email.com",
  "password": "secret"
}

### LOGIN

POST http://localhost:8080/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "Joakim",
  "password": "joakim"
}

### ALL USERS

GET  http://localhost:8080/api/users HTTP/1.1
content-type: application/json

### USER DETAILS

GET  http://localhost:8080/api/users/628fa6be716891a2262f7f98 HTTP/1.1
content-type: application/json

### UPDATE USER

PUT http://localhost:8080/api/users/628fa6be716891a2262f7f98 HTTP/1.1
content-type: application/json

{
  "username": "Joakim updated",
  "password": "secret"
}